@startuml Atividades

skinparam DefaultTextAlignment center
skinparam DefaultFontSize 12

start
:definir posições iniciais do tabuleiro;

repeat
    :seleciona o próximo jogador;
    :exibir tabuleiro;

    repeat
        :o jogador atual deve selecionar uma peça;
        :analisar se a peça selecionada é valida;
    repeat while (a peça é valida?) is (não)

    repeat
        repeat
            :o jogador atual deve escolher a nova posição para a peça;
            :analisar se a posição selecionada é valida;
        repeat while (posição valida?) is (não)

        :analisar se uma captura foi realizada;

        if (uma captura foi realizada?) then (sim)
            :remover a peça capturada;
        endif

        :move a peça selecionada;
        :exibir tabuleiro;
        :analisar se é possível realizar outra captura;
    repeat while (é possível realizar outra captura?) is (sim)

    :verificar se a peça selecionada pode se tornar uma dama;
    if (a peça selecionada pode se tornar uma dama?) then (sim)
        :converter a peça selecionada em dama;
    endif

    :verificar se houve uma vitória ou empate;
repeat while (é o fim do jogo?) is (não)

:exibe o nome do vencedor;
end

@enduml
